name: Build iOS App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Generate Xcode Project
        working-directory: ios-app
        run: xcodegen generate

      - name: Build app for Simulator
        working-directory: ios-app
        run: |
          xcodebuild clean build \
            -scheme "cowdar" \
            -project "cowdar.xcodeproj" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            -derivedDataPath build

      - name: Zip the .app bundle
        working-directory: ios-app/build/Build/Products/Debug-iphonesimulator
        run: zip -r SimulatorApp.zip "cowdar.app"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SimulatorApp
          path: ios-app/build/Build/Products/Debug-iphonesimulator/SimulatorApp.zip
